[package]
name = "lieweb"
version = "0.1.0"
authors = ["zzzdong <kuwater@163.com>"]
edition = "2018"

[dependencies]
bytes = "0.5"
futures-util = "0.3"
headers = "0.2"
http = "0.2"
hyper = "0.13"
lazy_static = "1.4"
mime = "0.3"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
tokio = "0.2"

[dev-dependencies]
tokio = { version="0.2", features=["full"] }
serde = { version="1.0", features=["derive"] }
