[package]
name = "lieweb"
version = "0.1.0"
authors = ["zzzdong <kuwater@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
headers = "0.2"
http = "0.2"
hyper = "0.13"
mime = "0.3"
serde = "1.0"
serde_json = "1.0"


[dev-dependencies]
tokio = { version="0.2", features=["full"] }
serde = { version="1.0", features=["derive"] }
